export const mockCustomers = [
  {
    id: '1',
    name: 'John Smith',
    email: 'john.smith@email.com',
    phone: '+1 (555) 123-4567',
    address: '123 Main Street, New York, NY 10001',
    dateOfBirth: '1985-03-15',
    createdAt: '2024-01-10',
    prescriptions: [],
    purchaseHistory: [],
  },
  {
    id: '2',
    name: 'Sarah Johnson',
    email: 'sarah.j@email.com',
    phone: '+1 (555) 234-5678',
    address: '456 Oak Avenue, Los Angeles, CA 90001',
    dateOfBirth: '1990-07-22',
    createdAt: '2024-01-08',
    prescriptions: [],
    purchaseHistory: [],
  },
  {
    id: '3',
    name: 'Michael Brown',
    email: 'm.brown@email.com',
    phone: '+1 (555) 345-6789',
    address: '789 Pine Road, Chicago, IL 60601',
    dateOfBirth: '1978-11-30',
    createdAt: '2024-01-05',
    prescriptions: [],
    purchaseHistory: [],
  },
];

export const mockSuppliers = [
  {
    id: '1',
    name: 'PharmaCorp Distributors',
    contactPerson: 'Robert Williams',
    email: 'orders@pharmacorp.com',
    phone: '+1 (800) 555-1234',
    address: '1000 Industrial Blvd, Newark, NJ 07102',
    paymentTerms: 'Net 30',
    createdAt: '2024-01-01',
  },
  {
    id: '2',
    name: 'MediHealth Supplies',
    contactPerson: 'Emily Chen',
    email: 'supply@medihealth.com',
    phone: '+1 (800) 555-5678',
    address: '2500 Medical Drive, Boston, MA 02101',
    paymentTerms: 'Net 45',
    createdAt: '2024-01-01',
  },
  {
    id: '3',
    name: 'Global Pharma Inc',
    contactPerson: 'David Martinez',
    email: 'sales@globalpharma.com',
    phone: '+1 (800) 555-9012',
    address: '500 Commerce Way, Dallas, TX 75201',
    paymentTerms: 'Net 30',
    createdAt: '2024-01-01',
  },
];

export const mockSales = [
  {
    id: '1',
    customerId: '1',
    customerName: 'John Smith',
    items: [
      {
        medicationId: '1',
        medicationName: 'Paracetamol 500mg',
        quantity: 2,
        unitPrice: 5.99,
        total: 11.98,
      },
      {
        medicationId: '5',
        medicationName: 'Omeprazole 20mg',
        quantity: 1,
        unitPrice: 9.99,
        total: 9.99,
      },
    ],
    subtotal: 21.97,
    tax: 1.76,
    discount: 0,
    total: 23.73,
    paymentMethod: 'card',
    status: 'completed',
    createdAt: '2024-12-24T10:30:00',
  },
  {
    id: '2',
    customerId: '2',
    customerName: 'Sarah Johnson',
    items: [
      {
        medicationId: '3',
        medicationName: 'Ibuprofen 400mg',
        quantity: 3,
        unitPrice: 7.49,
        total: 22.47,
      },
    ],
    subtotal: 22.47,
    tax: 1.8,
    discount: 2,
    total: 22.27,
    paymentMethod: 'cash',
    status: 'completed',
    createdAt: '2024-12-24T11:45:00',
  },
  {
    id: '3',
    customerName: 'Walk-in Customer',
    items: [
      {
        medicationId: '1',
        medicationName: 'Paracetamol 500mg',
        quantity: 1,
        unitPrice: 5.99,
        total: 5.99,
      },
    ],
    subtotal: 5.99,
    tax: 0.48,
    discount: 0,
    total: 6.47,
    paymentMethod: 'cash',
    status: 'completed',
    createdAt: '2024-12-24T14:20:00',
  },
];

export const mockPurchaseOrders = [
  {
    id: '1',
    supplierId: '1',
    supplierName: 'PharmaCorp Distributors',
    items: [
      {
        medicationId: '1',
        medicationName: 'Paracetamol 500mg',
        quantity: 500,
        unitCost: 3.5,
        total: 1750,
      },
      {
        medicationId: '3',
        medicationName: 'Ibuprofen 400mg',
        quantity: 300,
        unitCost: 4.5,
        total: 1350,
      },
    ],
    totalAmount: 3100,
    status: 'received',
    orderDate: '2024-12-20',
    receivedDate: '2024-12-23',
  },
  {
    id: '2',
    supplierId: '2',
    supplierName: 'MediHealth Supplies',
    items: [
      {
        medicationId: '2',
        medicationName: 'Amoxicillin 250mg',
        quantity: 200,
        unitCost: 8,
        total: 1600,
      },
    ],
    totalAmount: 1600,
    status: 'pending',
    orderDate: '2024-12-23',
  },
];
