import { Medication } from '@shared/models/medication';
import { SelectOption } from '@shared/models/user';

export const mockMedications: Medication[] = [
  {
    id: '1',
    name: 'Paracetamol 500mg',
    genericName: 'Acetaminophen',
    category: 'Pain Relief',
    manufacturer: 'PharmaCorp',
    batchNumber: 'PC-2024-001',
    expiryDate: '2025-06-15',
    quantity: 500,
    minStock: 100,
    unitPrice: 5.99,
    costPrice: 3.5,
    requiresPrescription: false,
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
  {
    id: '2',
    name: 'Amoxicillin 250mg',
    genericName: 'Amoxicillin',
    category: 'Antibiotics',
    manufacturer: 'MediHealth',
    batchNumber: 'MH-2024-102',
    expiryDate: '2025-03-20',
    quantity: 45,
    minStock: 50,
    unitPrice: 12.99,
    costPrice: 8,
    requiresPrescription: true,
    createdAt: '2024-01-10',
    updatedAt: '2024-01-10',
  },
  {
    id: '3',
    name: 'Ibuprofen 400mg',
    genericName: 'Ibuprofen',
    category: 'Pain Relief',
    manufacturer: 'HealthPlus',
    batchNumber: 'HP-2024-055',
    expiryDate: '2025-01-10',
    quantity: 200,
    minStock: 75,
    unitPrice: 7.49,
    costPrice: 4.5,
    requiresPrescription: false,
    createdAt: '2024-01-08',
    updatedAt: '2024-01-08',
  },
  {
    id: '4',
    name: 'Metformin 500mg',
    genericName: 'Metformin HCl',
    category: 'Diabetes',
    manufacturer: 'DiaCare',
    batchNumber: 'DC-2024-033',
    expiryDate: '2025-08-25',
    quantity: 30,
    minStock: 40,
    unitPrice: 15.99,
    costPrice: 10,
    requiresPrescription: true,
    createdAt: '2024-01-05',
    updatedAt: '2024-01-05',
  },
  {
    id: '5',
    name: 'Omeprazole 20mg',
    genericName: 'Omeprazole',
    category: 'Digestive',
    manufacturer: 'GastroMed',
    batchNumber: 'GM-2024-078',
    expiryDate: '2025-04-30',
    quantity: 150,
    minStock: 60,
    unitPrice: 9.99,
    costPrice: 6,
    requiresPrescription: false,
    createdAt: '2024-01-03',
    updatedAt: '2024-01-03',
  },
  {
    id: '6',
    name: 'Lisinopril 10mg',
    genericName: 'Lisinopril',
    category: 'Cardiovascular',
    manufacturer: 'CardioHealth',
    batchNumber: 'CH-2024-021',
    expiryDate: '2025-02-15',
    quantity: 80,
    minStock: 50,
    unitPrice: 18.99,
    costPrice: 12,
    requiresPrescription: true,
    createdAt: '2024-01-02',
    updatedAt: '2024-01-02',
  },
];

export const categoryOptions: SelectOption[] = [
  { label: 'Pain Relief', value: 'pain-relief' },
  { label: 'Antibiotics', value: 'antibiotics' },
  { label: 'Cold & Flu', value: 'cold-flu' },
  { label: 'Allergy', value: 'allergy' },
  { label: 'Diabetes', value: 'diabetes' },
  { label: 'Cardiovascular', value: 'cardiovascular' },
  { label: 'Digestive', value: 'digestive' },
  { label: 'Respiratory', value: 'respiratory' },
  { label: 'Mental Health', value: 'mental-health' },
  { label: 'Eye Care', value: 'eye-care' },
  { label: 'ENT', value: 'ent' },
  { label: 'Vitamins & Supplements', value: 'vitamins-supplements' },
  { label: 'Skin Care', value: 'skin-care' },
  { label: 'Women’s Health', value: 'womens-health' },
  { label: 'Pediatrics', value: 'pediatrics' },
  { label: 'Other', value: 'other' },
];
